apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This taks will clean up a workspace by deleteing all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
        - name: HOME
          value: '/tekton/home'
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all file from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the direcotry if it exists
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-custom
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"
  steps:
    - name: clone
      image: alpine/git:latest
      workingDir: $(workspaces.output.path)
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      script: |
        #!/bin/sh
        set -eu
        echo "Cloning $(params.url) ..."
        git clone $(params.url) repo
        cd repo
        git checkout $(params.revision)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-custom
spec:
  description: "Run flake8 linting in a restricted PSP-compliant container."
  workspaces:
    - name: source
  params:
    - name: args
      type: string
      default: "."
  steps:
    - name: flake8
      image: python:3.10-alpine
      workingDir: $(workspaces.source.path)
      env:
      - name: HOME
        value: /tekton/home
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      script: |
        #!/bin/sh
        set -eu

        # Add pip user install bin to PATH
        export PATH=$HOME/.local/bin:$PATH

        echo "Installing flake8..."
        pip install --no-cache-dir flake8

        echo "Running flake8 with args: $(params.args)"
        flake8 $(params.args) || true

